apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: revision-tracker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/WhySeriousKaif/devops-heros.git
    targetRevision: main
    path: capstone-devops-revision-tracker/helm/revision-tracker
    helm:
      releaseName: revision
      values: |
        frontend:
          image: ghcr.io/whyseriouskaif/revision-tracker-frontend
          tag: b6cd6a53066ce27dd279c00ceec04163153b7a70
          pullPolicy: IfNotPresent
        backend:
          image: ghcr.io/whyseriouskaif/revision-tracker-backend
          tag: b6cd6a53066ce27dd279c00ceec04163153b7a70
          pullPolicy: IfNotPresent
        hpa:
          enabled: false
        monitoring:
          serviceMonitor:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: revision-tracker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
