apiVersion: v1
kind: Service
metadata:
  name: revision-tracker-broken-service
  namespace: revision-tracker
spec:
  selector:
    app: label-that-does-not-exist
  ports:
    - port: 8000
      targetPort: 8000

