apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
  labels:
    app: emptydir-demo
spec:
  containers:
    - name: app
      image: nginx:1.27
      ports:
        - containerPort: 80
      volumeMounts:
        - name: app-storage
          mountPath: /data
  volumes:
    - name: app-storage
      emptyDir: {}
