apiVersion: v1
kind: Service
metadata:
  name: session20-app
  namespace: session20
  labels:
    app.kubernetes.io/managed-by: session20-gitops
spec:
  selector:
    app.kubernetes.io/name: session20-app
  ports:
    - name: http
      port: 80
      targetPort: http
