apiVersion: v1
kind: Service
metadata:
  name: devsecops-demo
  namespace: session17
spec:
  selector:
    app: devsecops-demo
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
